
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/musicreviews
      - PORT=5000

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

volumes:
  mongo-data: